In [96]:
!pip3 install scikit-learn

Requirement already satisfied: scikit-learn in .\.venv\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in .\.venv\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\.venv\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [97]:
import pandas as pd 

df = pd.read_csv("cardekho_dataset.csv")

df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  str
 2   brand              15411 non-null  str
 3   model              15411 non-null  str
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  str
 7   fuel_type          15411 non-null  str
 8   transmission_type  15411 non-null  str
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), str(6)
memory usage: 1.6 MB

In [121]:
# Dropping the unwanted colum in the dataset

df = df.drop(["Unnamed: 0"] , axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

In [100]:
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [120]:
df.columns

Index(['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats',
       'selling_price', 'brand_BMW', 'brand_Bentley', 'brand_Datsun',
       'brand_Ferrari', 'brand_Force', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_ISUZU', 'brand_Isuzu', 'brand_Jaguar',
       'brand_Jeep', 'brand_Kia', 'brand_Land Rover', 'brand_Lexus',
       'brand_MG', 'brand_Mahindra', 'brand_Maruti', 'brand_Maserati',
       'brand_Mercedes-AMG', 'brand_Mercedes-Benz', 'brand_Mini',
       'brand_Nissan', 'brand_Porsche', 'brand_Renault', 'brand_Rolls-Royce',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'seller_type_Individual', 'seller_type_Trustmark Dealer',
       'fuel_type_Diesel', 'fuel_type_Electric', 'fuel_type_LPG',
       'fuel_type_Petrol', 'transmission_type_Manual'],
      dtype='str')

In [102]:
brand_counts = df["brand"].value_counts()

In [103]:
# rare_brands = brand_counts[brand_counts < 200].index.tolist()

# df['brand'] = df['brand'].replace(rare_brands , "Others")

In [104]:
df['brand'].value_counts()

brand
Maruti           4992
Hyundai          2982
Honda            1485
Mahindra         1011
Toyota            793
Ford              790
Volkswagen        620
Renault           536
BMW               439
Tata              430
Mercedes-Benz     337
Skoda             334
Audi              192
Datsun            170
Jaguar             59
Land Rover         51
Jeep               41
Kia                32
Porsche            21
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
Maserati            2
ISUZU               2
Ferrari             1
Mercedes-AMG        1
Rolls-Royce         1
Force               1
Name: count, dtype: int64

In [119]:
df.shape

(15411, 45)

In [122]:
df

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,brand_BMW,brand_Bentley,brand_Datsun,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,9,120000,19.70,796,46.30,5,120000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
1,5,20000,18.90,1197,82.00,5,550000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
2,11,60000,17.00,1197,80.00,5,215000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
3,9,37000,20.92,998,67.10,5,226000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
4,6,30000,22.77,1498,98.59,5,570000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,9,10723,19.81,1086,68.05,5,250000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15407,2,18000,17.50,1373,91.10,7,925000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15408,6,67000,21.14,1498,103.52,5,425000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15409,5,3800000,16.00,2179,140.00,7,1225000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15410,2,13000,18.00,1497,117.60,5,1200000,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [123]:
df = df.drop(['car_name' , 'model'], axis = 1)

KeyError: "['car_name', 'model'] not found in axis"

In [124]:
df

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,brand_BMW,brand_Bentley,brand_Datsun,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,9,120000,19.70,796,46.30,5,120000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
1,5,20000,18.90,1197,82.00,5,550000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
2,11,60000,17.00,1197,80.00,5,215000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
3,9,37000,20.92,998,67.10,5,226000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
4,6,30000,22.77,1498,98.59,5,570000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,9,10723,19.81,1086,68.05,5,250000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15407,2,18000,17.50,1373,91.10,7,925000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15408,6,67000,21.14,1498,103.52,5,425000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15409,5,3800000,16.00,2179,140.00,7,1225000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15410,2,13000,18.00,1497,117.60,5,1200000,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [109]:
df = pd.get_dummies(df , columns=['brand', 'seller_type', 'fuel_type', 'transmission_type'] , drop_first=True)

In [125]:
df

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,brand_BMW,brand_Bentley,brand_Datsun,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,9,120000,19.70,796,46.30,5,120000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
1,5,20000,18.90,1197,82.00,5,550000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
2,11,60000,17.00,1197,80.00,5,215000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
3,9,37000,20.92,998,67.10,5,226000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
4,6,30000,22.77,1498,98.59,5,570000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,9,10723,19.81,1086,68.05,5,250000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15407,2,18000,17.50,1373,91.10,7,925000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15408,6,67000,21.14,1498,103.52,5,425000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15409,5,3800000,16.00,2179,140.00,7,1225000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15410,2,13000,18.00,1497,117.60,5,1200000,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [126]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [127]:
# Training and Testing Phase - Train and Test and Split

x = df.drop(columns=['selling_price'])
y = df['selling_price']

X_train , X_test, y_train, y_test = train_test_split(x, y , test_size=0.2 , random_state=42)

print(f"Train Set:- {X_train.shape[0]}")
print(f"Test set :- {X_test.shape[0]}")

Train Set:- 12328
Test set :- 3083

In [128]:
X_train.describe().round(1)

       vehicle_age  km_driven  mileage   engine  max_power    seats
count      12328.0    12328.0  12328.0  12328.0    12328.0  12328.0
mean           6.0    55423.6     19.7   1484.2      100.4      5.3
std            3.0    42477.8      4.2    521.3       42.8      0.8
min            0.0      581.0      4.0    793.0       38.4      0.0
25%            4.0    30000.0     17.0   1197.0       74.0      5.0
50%            6.0    50000.0     19.7   1248.0       88.5      5.0
75%            8.0    70000.0     22.7   1582.0      117.3      5.0
max           29.0  1325000.0     33.5   6592.0      626.0      9.0

In [129]:
df

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,brand_BMW,brand_Bentley,brand_Datsun,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,9,120000,19.70,796,46.30,5,120000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
1,5,20000,18.90,1197,82.00,5,550000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
2,11,60000,17.00,1197,80.00,5,215000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
3,9,37000,20.92,998,67.10,5,226000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
4,6,30000,22.77,1498,98.59,5,570000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,9,10723,19.81,1086,68.05,5,250000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15407,2,18000,17.50,1373,91.10,7,925000,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15408,6,67000,21.14,1498,103.52,5,425000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15409,5,3800000,16.00,2179,140.00,7,1225000,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15410,2,13000,18.00,1497,117.60,5,1200000,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [130]:
# Model Training Phase

numerical_cols = ['vehicle_age' ,'km_driven' , 'mileage','engine','max_power','seats']

scaler = StandardScaler()

X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

X_train

,vehicle_age,km_driven,mileage,engine,max_power,seats,brand_BMW,brand_Bentley,brand_Datsun,brand_Ferrari,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
11210,0.323969,0.349100,-2.050819,1.756765,2.681685,-0.403824,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
1347,-1.337798,-1.069394,0.985661,-0.547081,-0.382744,-0.403824,False,False,False,False,...,False,False,False,True,False,False,False,False,True,True
10363,-1.337798,-1.163564,-0.177042,0.893542,3.296910,-0.403824,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
316,0.323969,0.178369,-0.465315,0.024564,0.396229,-0.403824,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
10638,1.321030,0.585469,0.149668,-0.550917,-0.502047,-0.403824,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5191,0.323969,1.702310,0.248161,-0.453086,-0.270460,2.070500,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
13418,1.653383,0.084198,-0.876105,0.218310,0.066393,-0.403824,False,False,False,False,...,False,True,False,False,False,False,False,False,True,True
5390,0.323969,-0.833967,0.185702,-0.932654,-0.779483,-0.403824,False,False,False,False,...,False,False,False,True,False,False,False,False,True,True
860,-1.337798,-0.951680,-0.273133,-0.550917,-0.432805,-0.403824,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7270,-1.337798,-0.598540,0.130450,-0.042575,0.067563,-0.403824,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False

In [151]:
model = LinearRegression()

model.fit(X_train , y_train)

y_train_pred = model.predict(X_train)

y_train_pred

array([3412193.03734086,  538816.57194791, 3107972.2792696 , ...,
        315413.96838231,  792625.57941124, 1096655.71792075],
      shape=(12328,))

In [156]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae_train = mean_absolute_error(y_train , y_train_pred)

mae_train

199219.729004074

In [157]:
y_test_pred = model.predict(X_test)

In [158]:

mae_test = mean_absolute_error(y_test , y_test_pred)
mae_test

212761.44410581276

In [168]:
# Calculating the baseline

baseline_mean = df['selling_price'].mean().round(2)

baseline = abs(df['selling_price'] - baseline_mean)

mae = sum(baseline) / len(baseline)
mae_2 = baseline.mean()
mae

452669.92263448186

In [155]:
# compare = pd.DataFrame({
#     "y_test" :y_test,
#     "y_pred" : y_pred
# })
# print(compare.round(2))

In [171]:
train_r2 = r2_score(y_train, y_train_pred)
train_r2

0.8015753782439603

In [172]:
test_r2 = r2_score(y_test, y_test_pred)
test_r2

0.7359948378848242